version: "3.8"

services:
  db:
    image: mysql:8
    container_name: capstone-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # init script

  app:
    build: ./app
    container_name: capstone-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: users_db
      PORT: 3000
    depends_on:
      - db
    volumes:
      - ./app/public:/app/public     #- ./app/server.js:/app/server.js   # <-- Optional: mount server.js for live code changes

volumes:
  db_data:
